FROM jupyter/scipy-notebook

# install additional packages
# downgrade scikit-learn for eli5 to work
RUN mamba install --yes scrapy eli5 pipenv scikit-learn==1.2.0
RUN pip3 install bob structure

# The GPU packages
RUN mamba install --yes tensorflow pytorch torchvision lightgbm Keras chainer
RUN pip3 install pyodm cupy-cuda12x
